// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcpHaojsyI9AB8_quKfQ2i19UqJG-4Qjk',
    appId: '1:452088120781:web:b2020ae479e2f9c73e7084',
    messagingSenderId: '452088120781',
    projectId: 'flutter-chat-33ae8',
    authDomain: 'flutter-chat-33ae8.firebaseapp.com',
    storageBucket: 'flutter-chat-33ae8.appspot.com',
    measurementId: 'G-0W2MPMT506',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ8irHiGsMRTNV1z5iwhJJQ0i4UXx_SlA',
    appId: '1:452088120781:android:2add8139173ef3fe3e7084',
    messagingSenderId: '452088120781',
    projectId: 'flutter-chat-33ae8',
    storageBucket: 'flutter-chat-33ae8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfEBSAT3gxMNBuL65wjxYHd3kZU-BllKE',
    appId: '1:452088120781:ios:bdaf48500b754cef3e7084',
    messagingSenderId: '452088120781',
    projectId: 'flutter-chat-33ae8',
    storageBucket: 'flutter-chat-33ae8.appspot.com',
    iosClientId: '452088120781-u4u9cv9ofdqqhhf6kmhrphjtlg1jb58q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfEBSAT3gxMNBuL65wjxYHd3kZU-BllKE',
    appId: '1:452088120781:ios:bdaf48500b754cef3e7084',
    messagingSenderId: '452088120781',
    projectId: 'flutter-chat-33ae8',
    storageBucket: 'flutter-chat-33ae8.appspot.com',
    iosClientId: '452088120781-u4u9cv9ofdqqhhf6kmhrphjtlg1jb58q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
